### ISSUE TITLE
Apk wont show up

### ISSUE THREAD

**Issue by syedurashid** [xemulat/ReVancedPacker#15]
After the .exe does the entire process, it says apk file created and it cleaned the temp files. but the apk file doesnt show up in the folder, and the re-vanced cache folder stays there. Only MicroG.apk shows up, alongside with integrations.json, but no apk file.

Desktop: Windows 11

**Comment by xemulat** [comment]
attach a screenshot, 90% java error. Do you have Java 17 with Add to path enabled installed?

**Comment by xemulat** [comment]
issue closed
