### ISSUE TITLE
Patches are incompatible

### ISSUE THREAD

**Issue by ghost** [xemulat/ReVancedPacker#17]
Whenever I try to build the apk, the revanced patcher always says "WARNING *patch is incompatible with version 17.x.x." 

I have followed the steps on how to build the revanced apk, and have java 17 and python installed on my pc. 
![Screenshot (2)](https://user-images.githubusercontent.com/108929622/177968735-47bc0988-ef1d-4674-872a-3f74dc8136a4.png)

**Comment by xemulat** [comment]
This will be fixed soon

**Comment by xemulat** [comment]
Build with Disable compatibility check set to 1

**Comment by xemulat** [comment]
fixed
