### ISSUE TITLE
keystor error while compiling

### ISSUE THREAD

**Issue by hairy-tortoise** [xemulat/ReVancedPacker#19]
While compiling i get this error
`Traceback (most recent call last):
  File "revancedinstall.py", line 223, in <module>
NameError: name 'keystor' is not defined
[31264] Failed to execute script 'revancedinstall' due to unhandled exception!`

**Comment by hairy-tortoise** [comment]
The apk works fine, but the error is still there after trying multiple times

**Comment by lachlanjholmes** [comment]
+1 same error for me.

**Comment by xemulat** [comment]
Will fix in 2.0 (it's around the corner), all i can say is:
- It was a Python syntax error
- It was made by me (when compiling at 3am)
- Fix for now:
   Use .py version from code (remember to run pip install colorama in terminal first)

**Comment by xemulat** [comment]
Next version will be about graphics and UI

**Comment by xemulat** [comment]
fixed
