### ISSUE TITLE
cant find the revanced.apk

### ISSUE THREAD

**Issue by BiggieCheeseee** [xemulat/ReVancedPacker#27]
after the packer is done i cant find any revanced.apks in the folder

**Comment by xemulat** [comment]
Please send logs in form of screenshots of app usage

**Comment by AnilRana675** [comment]
> after the packer is done i cant find any revanced.apks in the folder

you need to download java from the revancedpacker.

**Comment by Mythodix** [comment]
Yeah I've had a similar problem with 2.0. 1.9 worked creating the APK but for some reason in 2.0 it's not creating the APK.

**Comment by xemulat** [comment]
Did you install Java 17 and added it to Path while installing?

**Comment by Mythodix** [comment]
> 

Got it working now. I ended up having to uninstall java and reinstall it. For some reason it wasn't installing correctly because the permissions in my windows directory were altered. All good now Thanks

**Comment by xemulat** [comment]
Np, closing...
