### ISSUE TITLE
Revanced APK does not work well when built in into system app

### ISSUE THREAD

**Issue by proganime1200** [xemulat/ReVancedPacker#29]
I get this error java.lang.RuntimeException: Unable to find a default SSL provider. I already added library files on the folder location itself but when I try to launch it when net is connected it force close it does open when there's no internet connection maybe if theres a root method
![Screenshot_2022-08-02-09-46-02-007_app revanced android youtube](https://user-images.githubusercontent.com/32473502/182274413-bb8eb2a4-bf19-46a9-8de7-bfda8b93b678.jpg)

**Comment by xemulat** [comment]
I don't know what may caused it, the issue is about ReVanced and not about ReVancedPacker. Create issue with ReVanced-Cli

**Comment by xemulat** [comment]
Stale

**Comment by proganime1200** [comment]
Nevermind i was able to make it system app by also including libraries so it boots now closing
