### ISSUE TITLE
Ability to select specific architecture

### ISSUE THREAD

**Issue by MF-Debug** [xemulat/ReVancedPacker#3]
Hello, is it possible to add an option to compile the apk for a specific architecture such as armv7, armv8, x86 etc.? Thanks!

**Comment by xemulat** [comment]
![image](https://user-images.githubusercontent.com/98595166/175608750-ffd89d3f-5b86-4c29-9b99-084520e0baaa.png)

The version i'm using have "universal" architecture

**Comment by MF-Debug** [comment]
Yes, I get that. But I was asking if it is possible to extract the individual architectures from this universal apk & compile them separately while the final apk with revanced is being prepared. In this way the size of the final apk would be much less than it is now currently.

**Comment by xemulat** [comment]
i can't do that with latest release 
![image](https://user-images.githubusercontent.com/98595166/175660218-cbac8397-4f68-4ad4-aaa7-5c48c9ad8a6b.png)
