### ISSUE TITLE
Wont open for me

### ISSUE THREAD

**Issue by hidebook** [xemulat/ReVancedPacker#32]
The Program wont open for me and gives me this text before closing
![image](https://user-images.githubusercontent.com/71184772/188698115-ea058405-4f45-464f-9bf4-212efac0b497.png)

**Comment by xemulat** [comment]
i will fix it in the next update, here's a sneek-peek:
![image](https://user-images.githubusercontent.com/98595166/188727453-ed0b8af2-cc87-4e84-b9b2-05cc419d56d0.png)

**Comment by MiltosDelis** [comment]
same here wont open for me and i cant see anything it close very fast

**Comment by xemulat** [comment]
i'm currently rewriting RVP with GUI so just wait 2-3 days

**Comment by xemulat** [comment]
Progress: 187 lines of code and no Java 17 Needed!

**Comment by xemulat** [comment]
206 lines <sup>404oops stop harassing me pls</sup>

**Comment by xemulat** [comment]
Almoast done...

**Comment by xemulat** [comment]
It will be fixed "soon"

**Comment by xemulat** [comment]
i'm compiling now...

**Comment by xemulat** [comment]
It is fixed now!
