### ISSUE TITLE
"App not installed" on non-root device

### ISSUE THREAD

**Issue by Ezzocorbi** [xemulat/ReVancedPacker#34]
I'm using version 2.1
I followed the steps in the guide,
on my PC the folder that I used to do the process looks like this:
![image](https://user-images.githubusercontent.com/36800339/189186465-32492fc1-0ece-484a-9286-25305a8c05ca.png)

I transferred, youtube.apk, integrations.apk, revanced.keystore and revanced.apk in a folder on my Galaxy A40, so it looks like this:
![Screenshot_20220908-192812_My_Files](https://user-images.githubusercontent.com/36800339/189187151-5fbf56db-85ef-455f-9c84-a04f7257fd3d.jpg)

(I'm not sure if I need to install integrations.apk).
When I try to install revanced.apk on my phone, I get this:
![Screenshot_20220908-192806_Package_installer](https://user-images.githubusercontent.com/36800339/189187192-38e237e1-1e37-44bb-ba06-1cdb6016222c.jpg)

What I've tried:
Install MicroG downloaded from https://www.apkmirror.com/apk/team-vanced/microg-youtube-vanced/
Restart my phone
Clear old files with Google Files app (even though I don't expect this to help in this context)
Install integrations.apk, it gave me the same error "App not installed"

More info:
I've used MicroG succesfully in the past with Vanced.

**Comment by xemulat** [comment]
you have to add "microg-support" in the "add integrations" section

**Comment by xemulat** [comment]
sorry for claiming it's added automatically:

![image](https://user-images.githubusercontent.com/98595166/189190772-e03b58ab-afa3-4fea-9efb-b0a7c718e033.png)

**Comment by EvoShishir** [comment]
we need a guide on how to pack the apk using v2.1

**Comment by Ezzocorbi** [comment]
I did everything again without adding "microg-support" but I'm still getting the same error

**Comment by xemulat** [comment]
you must add microg-support

**Comment by EvoShishir** [comment]
Hey Xemulat,
Will you please make a guide or video tutorial on how we can properly do it? I'm still confused on how to make the apk

**Comment by Ezzocorbi** [comment]
Thanks a lot! It's working now!
Adding microg-support fixed it.
By the way, there was another mistake I was making: I was using an unsupported version of the official Youtube app, so I downloaded version 17.33.42 which seems to work flawlessly.

**Comment by EvoShishir** [comment]
Hey Ezzocorbi, can you tell me step by step how you managed to install it?

**Comment by xemulat** [comment]
i'm creating a tutorial

**Comment by xemulat** [comment]
Fixed in 2.2 (GEOMETRY DASH REFERENCE OHMYGOSH) by making the process more clear

**Comment by khaisilk1910** [comment]
> Fixed in 2.2 (GEOMETRY DASH REFERENCE OHMYGOSH) by making the process more clear

Please guide for v2.2.
After pressing Build button and nothing else.
revanced-cache folder have created. But nothing file apk.

**Comment by channchetra** [comment]
@khaisilk1910 the same here on v2.2 after click Build there're only tools jar file show up nothing apk file show in foloderfolder.
![image](https://user-images.githubusercontent.com/12510711/189283779-9d91363b-2727-4cc4-8c00-555a46492a50.png)

**Comment by xemulat** [comment]
You don't have an apk file present, download it from the help menu

**Comment by channchetra** [comment]
@xemulat we need manual download both YouTube and microg?

**Comment by xemulat** [comment]
I will do that when I get home, or someone can just pull request that

**Comment by channchetra** [comment]
problem cuz I downloaded youtube unsupported version now. now it working. by the way after build I got only revanced.apk there're no MicroG.apk was build? is I need to install only revanced?

**Comment by channchetra** [comment]
I tried to install revaced.apk it's success but it's can't open until I manually install MicroG from old Vanced Manager app.

**Comment by khaisilk1910** [comment]
> You don't have an apk file present, download it from the help menu

I already have the file with the ReVancedPacker but no success.

**Comment by channchetra** [comment]
@khaisilk1910 if you downloaded unsupported version of youtube it'll now success try download youtube apk version 17.33.42 and build again.

**Comment by khaisilk1910** [comment]
> @khaisilk1910 if you downloaded unsupported version of youtube it'll now success try download youtube apk version 17.33.42 and build again.

Im tried again and success.
But Ads not remove. How to remove Ads?
Thanks

**Comment by khaisilk1910** [comment]
> @khaisilk1910 if you downloaded unsupported version of youtube it'll now success try download youtube apk version 17.33.42 and build again.
Skipping....

![Screenshot 2022-09-09 165416](https://user-images.githubusercontent.com/3167468/189323973-6183360f-5703-46d2-b3c6-3949cabaf994.png)

**Comment by channchetra** [comment]
try add this param to integrations box
`downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads`
![image](https://user-images.githubusercontent.com/12510711/189324427-782d7a94-4a20-4d18-9ecb-fe1c80b5ba6a.png)

**Comment by khaisilk1910** [comment]
> downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads
Many thank,
Well Done.

Can you give me full Param in integrations?

**Comment by channchetra** [comment]
> > downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads
> 
> Many thank, Well Done.
> 
> Can you give me full Param in integrations?

you can find here: 
https://github.com/revanced/revanced-patches#-patches
![image](https://user-images.githubusercontent.com/12510711/189328675-bece8965-374a-4f7e-bbec-2236d7731555.png)

**Comment by khaisilk1910** [comment]
> > > downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads
> > 
> > Many thank, Well Done.
> > 
> > Can you give me full Param in integrations?
> 
> you can find here: 
> https://github.com/revanced/revanced-patches#-patches
> ![image](https://user-images.githubusercontent.com/12510711/189328675-bece8965-374a-4f7e-bbec-2236d7731555.png)
> 

Many thanks
Why i can not playing in background and can not see P-T-P.
 when i turn off the screen or minimize the music stops immediately

**Comment by channchetra** [comment]
> > > > downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads
> > > 
> > > Many thank, Well Done.
> > > 
> > > Can you give me full Param in integrations?
> > 
> > you can find here: 
> > https://github.com/revanced/revanced-patches#-patches
> > ![image](https://user-images.githubusercontent.com/12510711/189328675-bece8965-374a-4f7e-bbec-2236d7731555.png)
> > 
> 
> Many thanks
> Why i can not playing in background and can not see P-T-P.
>  when i turn off the screen or minimize the music stops immediately 

The same here maybe the patched revanced not supported background playback yet 😣

**Comment by channchetra** [comment]
> > > > downloads swipe-controls seekbar-tapping amoled return-youtube-dislike premium-heading custom-branding hide-watermark theme microg-support settings remember-video-quality video-ads general-ads
> > > 
> > > Many thank, Well Done.
> > > 
> > > Can you give me full Param in integrations?
> > 
> > you can find here: 
> > https://github.com/revanced/revanced-patches#-patches
> > ![image](https://user-images.githubusercontent.com/12510711/189328675-bece8965-374a-4f7e-bbec-2236d7731555.png)
> > 
> 
> Many thanks
> Why i can not playing in background and can not see P-T-P.
>  when i turn off the screen or minimize the music stops immediately 

@khaisilk1910 if you need play in background you need add this param when build `minimized-playback`

**Comment by GollumArain** [comment]
**Help!** @xemulat @channchetra 

_Unable to Add Integrations_

I'm using Version 2.2. After entering integrations (patches), when I press **Enter** nothing happens. What I'm missing out? Do I need to add "colons" on side of each one or whole line. Thank You.

![2022-09-10_16-07-39](https://user-images.githubusercontent.com/72902553/189480629-ca9cd758-a13e-46f9-83b4-01f10135ebab.png)

**Comment by khaisilk1910** [comment]
> **Help!** @xemulat @channchetra 
> 
> _Unable to Add Integrations_
> 
> I'm using Version 2.2. After entering integrations (patches), when I press **Enter** nothing happens. What I'm missing out? Do I need to add "colons" on side of each one or whole line. Thank You.
> 
> ![2022-09-10_16-07-39](https://user-images.githubusercontent.com/72902553/189480629-ca9cd758-a13e-46f9-83b4-01f10135ebab.png)
>  

you have to press the Build button in the side column.

**Comment by khaisilk1910** [comment]
> **Help!** @xemulat @channchetra 
> 
> _Unable to Add Integrations_
> 
> I'm using Version 2.2. After entering integrations (patches), when I press **Enter** nothing happens. What I'm missing out? Do I need to add "colons" on side of each one or whole line. Thank You.
> 
> ![2022-09-10_16-07-39](https://user-images.githubusercontent.com/72902553/189480629-ca9cd758-a13e-46f9-83b4-01f10135ebab.png)
>  

you have to press the Build button in the side column.

**Comment by xemulat** [comment]
Press build, I will make sure to add enter as a trigger for building the app

**Comment by xemulat** [comment]
Reopened because the comments are still active

**Comment by channchetra** [comment]
Only problem for me right now is that there are no MicroG show up after building success.

**Comment by khaisilk1910** [comment]
> Only problem for me right now is that there are no MicroG show up after building success.

Me too 😂

**Comment by GollumArain** [comment]
> Only problem for me right now is that there are no MicroG show up after building success.

You can download MicroG from below link. But I think you already know that. I'm still posting, maybe helpful for someone else.

https://github.com/TeamVanced/VancedMicroG/releases

**Comment by GollumArain** [comment]
Patching any other supported app such as Reddit, Twitter & TikTok is not working. Script runs but no APK is generated. I think it's not supported by Revanced Packer.

**Comment by hikigayaaaa** [comment]
I have installed Revanced but its not launching. no error message, it is just automatically going back on main screen. thanks for any help in advance

**Comment by channchetra** [comment]
> > Only problem for me right now is that there are no MicroG show up after building success.
> 
> You can download MicroG from below link. But I think you already know that. I'm still posting, maybe helpful for someone else.
> 
> https://github.com/TeamVanced/VancedMicroG/releases

@hikigayaaaa you need to install MicroG and the download link can be seen in this comment.

**Comment by hikigayaaaa** [comment]
> > > Only problem for me right now is that there are no MicroG show up after building success.
> > 
> > 
> > You can download MicroG from below link. But I think you already know that. I'm still posting, maybe helpful for someone else.
> > https://github.com/TeamVanced/VancedMicroG/releases
> 
> @hikigayaaaa you need to install MicroG and the download link can be seen in this comment.

Thank you but I previously installed MicroG before installing Revanced tho? Maybe I'll wait for his tuts.

**Comment by ahmadsyarbini** [comment]
I downloaded the youtube apk, added all the needed parameters, pressed enter, and click build, java window pops out for 0.5 second and vanished. No revanced.apk were made.

**Comment by channchetra** [comment]
> 

which version of youtube.apk you downloaded? the patch support only 17.33.42 so if downloaded newer version than this you will got nothing after build.

**Comment by ahmadsyarbini** [comment]
> > 
> 
> which version of youtube.apk you downloaded? the patch support only 17.33.42 so if downloaded newer version than this you will got nothing after build.

yes I downloaded the 17.33.42

**Comment by khaisilk1910** [comment]
> I downloaded the youtube apk, added all the needed parameters, pressed enter, and click build, java window pops out for 0.5 second and vanished. No revanced.apk were made.

You can try uninstall java and reinstall it.
Then Windows + R and type %temp% then Enter and delete all in folder.
Then try build again.

**Comment by canerhoca** [comment]
I managed by renaming downloaded YouTube APK which is different as default starting with com.bla bla.  I renamed as YouTube.apk then process recognised it I think. Also you should type application name as YouTube in the first box. Give a try

**Comment by ahmadsyarbini** [comment]
> > I downloaded the youtube apk, added all the needed parameters, pressed enter, and click build, java window pops out for 0.5 second and vanished. No revanced.apk were made.
> 
> You can try uninstall java and reinstall it. Then Windows + R and type %temp% then Enter and delete all in folder. Then try build again with Run with Administrator.

Done all that. Still doesn't work.

**Comment by khaisilk1910** [comment]
> i downloaded the youtube app version  17.33.42 does it need to be in the same folder(1)
> ![11111](https://user-images.githubusercontent.com/113538066/190198133-9171bde6-f77b-4303-8fd7-34443743c7f8.png)
> ?? and what do i write in here(2)
> ![2222](https://user-images.githubusercontent.com/113538066/190198177-ab38138f-f86c-4890-a5b4-c2bb603e1335.png)

put the Youtube.apk file together with the patcher file.Delete all existing files and folders. except Youtube and patcher.then run the patcher again with Admin rights. Enter the Youtube file name and Enter.

**Comment by xemulat** [comment]
you don't have the youtube.apk file inside RVP's folder

**Comment by ahmadsyarbini** [comment]
> > i downloaded the youtube app version  17.33.42 does it need to be in the same folder(1)
> > ![11111](https://user-images.githubusercontent.com/113538066/190198133-9171bde6-f77b-4303-8fd7-34443743c7f8.png)
> > ?? and what do i write in here(2)
> > ![2222](https://user-images.githubusercontent.com/113538066/190198177-ab38138f-f86c-4890-a5b4-c2bb603e1335.png)
> 
> put the Youtube.apk file together with the patcher file.Delete all existing files and folders. except Youtube and patcher.then run the patcher again with Admin rights. Enter the Youtube file name and Enter.

I did that. Still doesn't work. Not sure what else to do. I'm out of ideas.

**Comment by Yjuser1** [comment]
Can you post the latest version of the tutorial? thanks
