### ISSUE TITLE
Unhappy with GUI update AND version 2.0 crashing after a few seconds

### ISSUE THREAD

**Issue by suLac4ever** [xemulat/ReVancedPacker#35]
Frankly I don't like the GUI update at all.
Before, everything was easy to use and straight forward.
Now, to use the packer you have to know many stirngs of text to get the vanced apk.
Some dropdown or multible choice / checkbox system would be very helpful, because the program is unusable without clicking "help" every single step of the way ... and until I figure it out completely I am unable to get anything done at all.

I wish the original terminal like program would still work, because I would prefer to use that instead, but sadly it appears to got broken after the GUI update. When running version 2.0 it now crashes / closes after a few seconds without doing anything.

**Comment by xemulat** [comment]
I will do the same version in cli, but not now

**Comment by xemulat** [comment]
I will use my library XeLib to build it faster tho

**Comment by eternialz** [comment]
For me, the GUI crashed when starting the java command to build. That was because the youtube APK wasn't in the folder. After manually downloading and placing it next to the .exe, I managed to build it using the same command that ReVancedPacker used from another terminal

**Comment by Oppa-YA** [comment]
> For me, the GUI crashed when starting the java command to build. That was because the youtube APK wasn't in the folder. After manually downloading and placing it next to the .exe, I managed to build ReVanced using the same command that ReVancedPacker used from another terminal. The MicroG apk wasn't there either at the end, maybe because it crashed before fetching it.

Hi! Did you managed to get it to work and get patched microg? Do you need to download microg and place it in same folder?

**Comment by Oppa-YA** [comment]
> I will do the same version in cli, but not now
Hello, can you please explain how to get current version with GUI to work?
I figured it out to place original youtube.apk in the same folder and got patched vanced.apk. But i did not get the microg at the output, do i need to download and place it in the same folder?

**Comment by eternialz** [comment]
> Hi! Did you managed to get it to work and get patched microg? Do you need to download microg and place it in same folder?

@Oppa-YA I downloaded the patched vanced microg.apk on the vanded team github there : https://github.com/TeamVanced/VancedMicroG/releases

**Comment by Oppa-YA** [comment]
> > Hi! Did you managed to get it to work and get patched microg? Do you need to download microg and place it in same folder?
> 
> @Oppa-YA I downloaded the patched vanced microg.apk on the vanded team github there : https://github.com/TeamVanced/VancedMicroG/releases. I installed the microg.apk and the patched apk from ReVancedPacker and they work well on a non rooted device.

Thank you, it works!
