### ISSUE TITLE
Can't install apk once built on a rooted device

### ISSUE THREAD

**Issue by lihuelworks** [xemulat/ReVancedPacker#36]
**Describe the bug**
I'm using the new GUI, and successfully building the apk, but I cannot install it on my rooted phone.

**To Reproduce**
1. Start ReVancedPacker (last version with GUI)
2. Enter "youtube" as apk name
3. Set "downloads seekbar-tapping amoled disable-create-button hide-cast-button return-youtube-dislike premium-heading disable-fullscreen-panels hide-shorts-button hide-watermark sponsorblock enable-wide-searchbar tablet-mini-player minimized-playback client-spoof settings custom-playback-speed remember-video-quality video-ads general-ads hide-infocard-suggestions" as integrations
5. Build apk
6. Grab said .apk and put it on downloads folder. Try to install .apk.

**Expected behavior**
App gets installed.

**Actual behavior**

This is shown, and apk cannot be installed:
![c6be4abe-03d0-477f-a0da-8f50012fd1d8](https://user-images.githubusercontent.com/49965980/189553662-53671bae-7d76-4164-b9d2-3823858db986.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Evolution X ROM, Poco F3 (Alioth) 
 - Version: evolution_alioth-ota-tp1a.220905.004-09072036.zip

**Additional context**
- Latest Magisk version
- Orangefox recovery

**Comment by xemulat** [comment]
It works on non-rooted devices, I don't know

**Comment by lihuelworks** [comment]
Maybe it's always packaging with Micro G? Rooted devices don't need Micro G, and that may be the issue.

**Comment by xemulat** [comment]
It isn't packing with microg, I will fix everything and remove the GUI in the next update

**Comment by ltstereo** [comment]
I have the same problem. Coming from 2.0, that worked. I am rooted on Android 13. "You cant´t install the app on your device"
