### ISSUE TITLE
2.1 update breaks the compatibility with MacOS and Linux using Python script

### ISSUE THREAD

**Issue by laiduy98** [xemulat/ReVancedPacker#38]
With the old version, the Python script can run also on MacOS and Linux. In the next version, it would be great if the script is multi platform.

I think it could be fixed by changing the command related to java. If the OS detected is Windows, so we make it `java.exe`, otherwise only `java`.

**Comment by xemulat** [comment]
ok

**Comment by xemulat** [comment]
will fix
