### ISSUE TITLE
Skip version checking

### ISSUE THREAD

**Issue by MF-Debug** [xemulat/ReVancedPacker#4]
**Is your feature request related to a problem? Please describe.**
Right now, we are using the latest stable youtube apk. I want the ability to test youtube beta apk as well.

**Describe the solution you'd like**
Implementing the --debugging parameter while patching would give us the possibility to do this.

**Describe alternatives you've considered**
Maybe we can download & place our preferred youtube apk in the directory instead of the script downloading it for us before doing this? 

**Additional context**
As seen from the discussion [here](https://www.reddit.com/r/revancedapp/comments/vg2mjf/revanced_works_with_the_latest_version_of_youtube/)

**Comment by xemulat** [comment]
Okey, will do in 1.6

**Comment by xemulat** [comment]
Almost done

**Comment by xemulat** [comment]
Done, compiled for 1.6!
