### ISSUE TITLE
Latest update doesn't properly work

### ISSUE THREAD

**Issue by AXVIII3** [xemulat/ReVancedPacker#40]
The app works perfectly till downloading integrations and crashes afterwards. I have python 3.10.9 and jdk 17 pre installed in my system btw but that should not affect anything I think. Using Windows 10 Enterprise 22H2.

Click on .exe file. Downloads Integrations, Patches, CLI successfully. Then crashes.
This is the folder structure after crash
![image](https://user-images.githubusercontent.com/76608488/206229042-22be94ab-f4f7-43f7-bab7-7d05a9a73265.png)

The command prompt shows this error immediately afterwards
![image](https://user-images.githubusercontent.com/76608488/206229819-4093627d-373d-405d-85d0-906b98bb27f0.png)

If I run the .exe again it shows this and continue to show the error above after briefly showing >Setting Up
![image](https://user-images.githubusercontent.com/76608488/206230122-b162d734-62ef-45c1-9363-34e9cee4d28d.png)

 - OS: Windows
 - 10 Enterprise 22H2

**Comment by AXVIII3** [comment]
Tried 2.2 Hotfix 1
![image](https://user-images.githubusercontent.com/76608488/206230824-e0b044c6-8646-42a1-826c-684a6006e21b.png)

**Comment by AXVIII3** [comment]
Tried 2.1
![image](https://user-images.githubusercontent.com/76608488/206231345-b6210dbe-181c-4188-9e04-20238f2bd1f2.png)

**Comment by xemulat** [comment]
Check your internet.

**Comment by AXVIII3** [comment]
> Check your internet.

My internet was all right. That day it was around 20mbps.

**Comment by AXVIII3** [comment]
Tried again today. No luck
![image](https://user-images.githubusercontent.com/76608488/206627998-f8ee167f-14f4-42d9-b63b-be15447276a8.png)

Internet a bit under the weather today, but it works just fine.
![image](https://user-images.githubusercontent.com/76608488/206628121-0309c7d0-07c7-4f73-aa2f-3469717a51b9.png)

**Comment by canerhoca** [comment]
Did you try with proxy ?

**Comment by xemulat** [comment]
![image](https://user-images.githubusercontent.com/98595166/206649893-7e8c37fd-e9f9-471a-85cf-4fd412aad66e.png)

**Comment by xemulat** [comment]
so yea

**Comment by xemulat** [comment]
check the updated readme

**Comment by AXVIII3** [comment]
Damn... that sucks. I guess I'll just close the issue now

**Comment by AXVIII3** [comment]
BTW what should I do now? I tried keeping the patches.jar in the same folder as the .exe and running. But it still tried to download them and crashes. SO?

**Comment by xemulat** [comment]
I don't know how to help you then.
