### ISSUE TITLE
Revanced not opening

### ISSUE THREAD

**Issue by DevilFox2** [xemulat/ReVancedPacker#43]
The app is opening but closes immediately.

My S22 ultra is saying that "YouTube ReVanced has a bug"

**Comment by xemulat** [comment]
"YouTube ReVanced has a bug"

Can you show some screenshots?

**Comment by DevilFox2** [comment]
i'll try to get a screenshot, i've tried the Revanced manager and i've also been getting the same results. The app crashes when i try to open it.

**Comment by xemulat** [comment]
closed cuz you said it's solved on Discord
