### ISSUE TITLE
revanced.apk never gets built

### ISSUE THREAD

**Issue by sm64onlydude** [xemulat/ReVancedPacker#5]
so after i used the app, when it says revanced.apk built nothing actually happens and the apk is nowhere to be seen except for the microg apk

**Comment by xemulat** [comment]
You can try dragging the app file (.exe) to cmd windows, and what os do you use

**Comment by xemulat** [comment]
From there you can use program called lightshot to copy selected area of the screen to clipboard

**Comment by gris-0** [comment]
same problem here, running it on win10 and using it through cmd didn't help sadly 
![cmd_GdhSX8yrMM](https://user-images.githubusercontent.com/108252244/175862649-4abcdb69-ee8b-4cd9-aee4-1b2b6e16c41e.png)

**Comment by xemulat** [comment]
I use Adoptium Java 17 with Add To PATH enabled, and it works fine

**Comment by xemulat** [comment]
Issue is solved, closing
