### ISSUE TITLE
Error while creating revanced.apk

### ISSUE THREAD

**Issue by CitrusOranges** [xemulat/ReVancedPacker#6]
While am using the app i notice some error in app in the final step Signing revanced_aligned.apk show some error and the Revanced.apk is not there in folder only mircoG.apk this is picture of error - https://imgur.com/a/LA67vPK

**Comment by xemulat** [comment]
Try running .py version from code, but you must install python and run "pip install colorama" in powershell (color library i use)

**Comment by xemulat** [comment]
And i'm sure it works on windows 11

**Comment by LucasGenoud** [comment]
Yeah i have the exact same issue

**Comment by CitrusOranges** [comment]
> Try running .py version from code, but you must install python and run "pip install colorama" in powershell (color library i use)

Still Revanced.apk not appear in v1.7 and same issue at the last step of packaging of apk - https://imgur.com/a/NU2HGeN

**Comment by xemulat** [comment]
Clean temp files, Download .py version, install colorama, should work
